= Neo4j GraphGist =

:neo4j-version: 2.0.0-RC1
:author: Anders Nawroth
:twitter: @nawroth
:tags: domain:example

Neo4j GraphGists are a way to share documents including Cypher queries.
The queries can be executed in an online console.
GraphGists can be used to share examples or ideas or outline a question you have.

See also the https://github.com/neo4j-contrib/graphgist/wiki[GraphGist Collection] and check out the *http://blog.neo4j.org/2013/10/the-first-graphgist-challenge-completed.html[results of the first GraphGist Challenge]*!

You create a GraphGist by creating a https://gist.github.com/[GitHub Gist] in http://asciidoctor.org/docs/asciidoc-quick-reference/[AsciiDoc] and enter the URL to it in the form on this page.
The GraphGist is just as private as the GitHub Gist you created.
To share a GraphGist, just share the URL the page gets after entering the Gist in the form.

For instructions, see:

++++
<iframe src="//player.vimeo.com/video/74279113" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="http://vimeo.com/74279113">How to create a Neoj4 GraphGist</a> from <a href="http://vimeo.com/user1375223">Peter Neubauer</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
++++

* link:./?github-neo4j-contrib%2Fgists%2F%2Fmeta%2FSimple.adoc[A simple GraphGist]
* link:./?github-neo4j-contrib%2Fgists%2F%2Fmeta%2FHowTo.adoc[How to create a GraphGist]

This is what the result can look like:

//console

A first simple query to just create a node:

[source,cypher]
----
CREATE (n{name:'first node'});
----

NOTE: This document is a GraphGist, use the Page Source button on top of the page to see the document behind it.

== Examples

* link:./?5956880[Create nodes and relationships]

